export const typeTranslations = {
    cities: "Города",
    feyspires: "Замки эльфов",
    forts: "Форты",
    castles: "Замки",
    fortresses: "Крепости",
    inns: "Таверны",
    settlements: "Поселения",
    elvenwood_settlements: "Поселения",
    towns: "Города",
    dungeons: "Подземелья",
    tombs: "Склепы",
    caves: "Пещеры",
    landmarks: "Место",
    ruins: "Руины",
    elder_ruins: "Руины",
    town_ruins: "Руины",
    temples: "Храмы",
    enclaves: "Анклавы",
    mountains: "Горы", 
    rivers: "Рекя",
    seas: "Моря"
};

export const iconUrls = {
    cities: "images/icons/cities.png",
    feyspires: "images/icons/feyspires.png",
    forts: "images/icons/forts.png",
    castles: "images/icons/castles.png",
    fortresses: "images/icons/fortresses.png",
    secrets: "images/icons/secrets.png", 
    settlements: "images/icons/settlements.png",
    towns: "images/icons/towns.png",
    dungeons: "images/icons/dungeons.png",
    tombs: "images/icons/tombs.png",
    caves: "images/icons/caves.png",
    landmarks: "images/icons/poi.png",
    ruins: "images/icons/ruins.png",
    elder_ruins: "images/icons/elder_ruins.png",
    town_ruins: "images/icons/town_ruins.png",
    shrines: "images/icons/shrines.png",
    enclaves: "images/icons/enclaves.png",
    gold_dragon: "images/icons/gold_dragon.png",
    malacoth: "images/icons/malacoth.png",
    sapphire: "images/icons/sapphire.png"    
};