export const typeTranslations = {
    cities: "Города",
    feyspires: "Замки эльфов",
    forts: "Форты",
    castles: "Замки",
    fortresses: "Крепости",
    inns: "Таверны",
    settlements: "Поселения",
    feyspires: "Поселения",
    dungeons: "Подземелья",
    tombs: "Склепы",
    caves: "Пещеры",
    points_of_interest: "Место",
    ruins: "Руины",
    shrines: "Храмы",
    enclaves: "Анклавы",
};

export const iconUrls = {
    cities: "images/icons/cities.png",
    feyspires: "images/icons/feyspires.png",
    forts: "images/icons/forts.png",
    castles: "images/icons/castles.png",
    secrets: "images/icons/secrets.png", 
    settlements: "images/icons/settlements.png",
    dungeons: "images/icons/dungeons.png",
    tombs: "images/icons/tombs.png",
    caves: "images/icons/caves.png",
    points_of_interest: "images/icons/poi.png",
    ruins: "images/icons/ruins.png",
    shrines: "images/icons/shrines.png",
    enclaves: "images/icons/enclaves.png",
    gold_dragon: "images/icons/gold_dragon.png",
    malacoth: "images/icons/malacoth.png",
    sapphire: "images/icons/sapphire.png"    
};